import { useState, useMemo } from 'react'
import { motion } from 'framer-motion'
import { Copy, Check, Download, Terminal, ChevronDown } from 'lucide-react'
import type { ReconciliationResult } from '../../types'
import { showToast } from '../../lib/toast'
import { cn } from '@/lib/utils'

interface Props { result: ReconciliationResult }
type Format = 'sql' | 'json' | 'python'

export default function MigrationScaffold({ result }: Props) {
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState<Format>('sql')
  const [showFormatMenu, setShowFormatMenu] = useState(false)

  const sqlCode = typeof result.migration_scaffold === 'string' && result.migration_scaffold
    ? result.migration_scaffold
    : '-- No migration scaffold generated.'

  const code = useMemo(() => {
    if (format === 'sql') return sqlCode
    if (format === 'json') {
      const data = {
        source_schema: result.summary.tables_in_a,
        target_schema: result.summary.tables_in_b,
        tables_matched: result.summary.tables_matched,
        average_confidence: result.summary.average_confidence,
        conflicts: result.summary.total_conflicts,
        mappings: result.table_mappings.map(m => ({
          source: m.table_a.name,
          target: m.table_b.name,
          confidence: m.confidence,
          columns: m.column_mappings.length,
        })),
      }
      return JSON.stringify(data, null, 2)
    }
    if (format === 'python') {
      const lines = [
        '# Database schema reconciliation mapping',
        '# Auto-generated by SchemaSync',
        '',
        'MAPPING = {',
        `  "source_schema": "${result.summary.tables_in_a} tables",`,
        `  "target_schema": "${result.summary.tables_in_b} tables",`,
        `  "matched_tables": ${result.summary.tables_matched},`,
        `  "average_confidence": ${result.summary.average_confidence.toFixed(4)},`,
        `  "conflicts": ${result.summary.total_conflicts},`,
        '  "table_mappings": [',
        ...result.table_mappings.map(m =>
          `    {"source": "${m.table_a.name}", "target": "${m.table_b.name}", "confidence": ${m.confidence.toFixed(4)}},`
        ),
        '  ]',
        '}',
      ]
      return lines.join('\n')
    }
    return sqlCode
  }, [format, sqlCode, result])

  const lines = code.split('\n')
  const byteSize = new Blob([code]).size
  const sizeLabel = byteSize < 1024 ? `${byteSize} B` : `${(byteSize / 1024).toFixed(1)} KB`

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      showToast(`${format.toUpperCase()} code copied to clipboard`, 'success')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      showToast('Failed to copy code', 'error')
    }
  }

  const handleDownload = () => {
    try {
      const a = document.createElement('a')
      const mimeTypes = { sql: 'text/plain', json: 'application/json', python: 'text/plain' }
      a.href = URL.createObjectURL(new Blob([code], { type: mimeTypes[format] }))
      a.download = `migration.${format}`
      a.click()
      showToast(`migration.${format} downloaded`, 'success')
    } catch {
      showToast('Failed to download file', 'error')
    }
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <Terminal className="h-4 w-4 text-white/30" />
          <div className="relative">
            <button
              onClick={() => setShowFormatMenu(!showFormatMenu)}
              className="flex items-center gap-1.5 rounded-md border border-white/[0.06] bg-white/[0.03] px-2.5 py-0.5 text-sm font-medium text-white/70 transition-colors hover:border-white/12 hover:bg-white/[0.05]"
            >
              <span>migration.{format}</span>
              <ChevronDown className="h-3 w-3 text-white/30" />
            </button>
            {showFormatMenu && (
              <motion.div
                initial={{ opacity: 0, y: -2 }}
                animate={{ opacity: 1, y: 0 }}
                className="absolute top-full mt-1 rounded-lg border border-white/[0.12] bg-[#0a0a12]/95 backdrop-blur-sm z-10 overflow-hidden shadow-lg"
              >
                {(['sql', 'json', 'python'] as const).map(fmt => (
                  <button
                    key={fmt}
                    onClick={() => { setFormat(fmt); setShowFormatMenu(false) }}
                    className={cn(
                      'block w-full px-4 py-2 text-left text-sm transition-colors',
                      format === fmt ? 'bg-indigo-600/20 text-indigo-300 font-medium' : 'text-white/50 hover:bg-white/[0.08] hover:text-white/80'
                    )}
                  >
                    .{fmt}
                  </button>
                ))}
              </motion.div>
            )}
          </div>
          <span className="rounded-md border border-white/[0.06] bg-white/[0.03] px-2 py-0.5 text-[11px] text-white/25">
            {lines.length} lines · {sizeLabel}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <IconButton onClick={handleCopy} title="Copy">
            <motion.span
              key={copied ? 'check' : 'copy'}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              className="flex items-center gap-1.5"
            >
              {copied ? (
                <><Check className="h-3.5 w-3.5 text-emerald-400" /><span className="text-emerald-400">Copied</span></>
              ) : (
                <><Copy className="h-3.5 w-3.5" /><span>Copy</span></>
              )}
            </motion.span>
          </IconButton>

          <IconButton onClick={handleDownload} title="Download">
            <Download className="h-3.5 w-3.5" />
            <span>Download</span>
          </IconButton>
        </div>
      </div>

      {/* Code block */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="overflow-hidden rounded-xl border border-white/[0.1] shadow-[0_8px_32px_rgba(0,0,0,0.3)]"
      >
        {/* Traffic-light bar */}
        <div className="flex items-center gap-1.5 border-b border-white/[0.06] bg-gradient-to-r from-white/[0.04] to-white/[0.02] px-4 py-3">
          <motion.div
            animate={{ scale: [1, 1.2, 1] }}
            transition={{ duration: 2, repeat: Infinity, delay: 0 }}
            className="h-2.5 w-2.5 rounded-full bg-rose-400/60"
          />
          <motion.div
            animate={{ scale: [1, 1.2, 1] }}
            transition={{ duration: 2, repeat: Infinity, delay: 0.2 }}
            className="h-2.5 w-2.5 rounded-full bg-amber-400/60"
          />
          <motion.div
            animate={{ scale: [1, 1.2, 1] }}
            transition={{ duration: 2, repeat: Infinity, delay: 0.4 }}
            className="h-2.5 w-2.5 rounded-full bg-emerald-400/60"
          />
          <span className="ml-3 text-[11px] font-medium text-white/40 uppercase tracking-wider">{format}</span>
        </div>

        <div className="max-h-[520px] overflow-auto bg-gradient-to-b from-[#0a0a14] to-[#06060e] custom-scrollbar">
          <pre className="p-5 text-[0.8125rem] leading-relaxed font-mono">
            <code>
              {lines.map((line, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: -4 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: Math.min(i * 0.01, 0.3), duration: 0.3 }}
                  className="flex hover:bg-white/[0.04] transition-colors"
                >
                  <span className="mr-4 w-8 shrink-0 select-none text-right text-white/[0.2] tabular-nums font-semibold">
                    {i + 1}
                  </span>
                  {format === 'sql' ? <SqlLine line={line} /> : <span className="text-white/60">{line}</span>}
                </motion.div>
              ))}
            </code>
          </pre>
        </div>
      </motion.div>

      {/* Tip */}
      <p className="text-xs text-white/20 leading-relaxed">
        Review this scaffold before running in production — type casts and constraints may need manual adjustment.
      </p>
    </div>
  )
}

function SqlLine({ line }: { line: string }) {
  if (line.startsWith('--')) {
    return <span className="text-white/[0.35] italic">{line}</span>
  }
  const keywords = /\b(BEGIN|COMMIT|CREATE|TABLE|IF|NOT|EXISTS|INSERT|INTO|SELECT|FROM|CAST|AS|NULL|DEFAULT|PRIMARY|KEY|INDEX|UNIQUE|ON|REFERENCES|WHERE|AND|OR|SET)\b/g

  const parts: { text: string; isKw: boolean }[] = []
  let last = 0
  let match: RegExpExecArray | null
  while ((match = keywords.exec(line)) !== null) {
    if (match.index > last) parts.push({ text: line.slice(last, match.index), isKw: false })
    parts.push({ text: match[0], isKw: true })
    last = match.index + match[0].length
  }
  if (last < line.length) parts.push({ text: line.slice(last), isKw: false })

  return (
    <span>
      {parts.map((p, i) =>
        p.isKw ? (
          <span key={i} className="text-cyan-300/80 font-semibold">{p.text}</span>
        ) : (
          <span key={i} className="text-white/60">{p.text}</span>
        )
      )}
    </span>
  )
}

function IconButton({ children, onClick, title }: { children: React.ReactNode; onClick: () => void; title: string }) {
  return (
    <motion.button
      onClick={onClick}
      title={title}
      whileHover={{ scale: 1.05, y: -1 }}
      whileTap={{ scale: 0.98 }}
      className={cn(
        'relative overflow-hidden flex items-center gap-1.5 rounded-lg border border-white/[0.1] bg-gradient-to-br from-white/[0.08] to-white/[0.02]',
        'px-3 py-1.5 text-xs font-semibold text-white/60',
        'transition-all hover:border-white/[0.18] hover:bg-gradient-to-br hover:from-white/[0.12] hover:to-white/[0.04] hover:text-white/90',
        'shadow-[0_4px_16px_rgba(0,0,0,0.2)] hover:shadow-[0_8px_24px_rgba(0,0,0,0.3)]'
      )}
    >
      <motion.span
        whileHover={{ scale: 1.1 }}
        className="flex items-center"
      >
        {children}
      </motion.span>
    </motion.button>
  )
}
